import { prisma } from "@/lib/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { redirect } from "next/navigation";
import Link from "next/link";

export default async function AccountEarningsPage() {
    const session = await getServerSession(authOptions);
    // @ts-ignore
    if (session?.user?.role !== "MANAGER") {
        redirect("/dashboard");
    }

    // Fetch all accounts that have been worked on (have earnings data)
    const accountsWithEarnings = await prisma.workAccount.findMany({
        where: {
            finalEarnings: { not: null },
        },
        include: {
            employee: true,
        },
        orderBy: {
            accountName: "asc"
        }
    });

    // Group by account name and calculate totals
    const accountSummary = accountsWithEarnings.reduce((acc: Record<string, {
        accountName: string;
        sessions: any[];
        totalEarned: number;
        sessionsCount: number;
        uniqueEmployees: Set<string>;
    }>, account) => {
        const accountName = account.accountName;
        
        if (!acc[accountName]) {
            acc[accountName] = {
                accountName,
                sessions: [],
                totalEarned: 0,
                sessionsCount: 0,
                uniqueEmployees: new Set(),
            };
        }
        
        const initial = account.initialEarnings ? parseFloat(account.initialEarnings.toString()) : 0;
        const final = account.finalEarnings ? parseFloat(account.finalEarnings.toString()) : 0;
        const earned = final - initial;
        
        acc[accountName].sessions.push({
            ...account,
            earned: earned
        });
        acc[accountName].totalEarned += earned;
        acc[accountName].sessionsCount += 1;
        // Count both known employees and unknown ones as separate workers
        const employeeName = account.employee?.username || `Unknown-${account.id}`;
        acc[accountName].uniqueEmployees.add(employeeName);
        
        return acc;
    }, {});

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-bold text-white">Account Earnings Report</h1>
                    <p className="text-sm text-gray-400 mt-1">View earnings generated by each account across all workers</p>
                </div>
                <Link href="/manager/dashboard" className="inline-flex items-center rounded-md bg-gray-600 px-3 py-2 text-sm font-medium text-white hover:bg-gray-700">
                    <svg className="mr-2 h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
                    Back to Dashboard
                </Link>
            </div>

            {Object.keys(accountSummary).length === 0 ? (
                <div className="bg-gray-800 rounded-lg shadow-lg border border-gray-700 p-12 text-center">
                    <svg className="mx-auto h-12 w-12 text-gray-600 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                    </svg>
                    <h3 className="text-lg font-medium text-white mb-2">No Earnings Data</h3>
                    <p className="text-gray-400">No accounts have been completed yet.</p>
                </div>
            ) : (
                <div className="space-y-4">
                    {Object.values(accountSummary).map(({ accountName, sessions, totalEarned, sessionsCount, uniqueEmployees }) => (
                        <details key={accountName} className="bg-gray-800 rounded-lg shadow-lg border border-gray-700 overflow-hidden group">
                            <summary className="cursor-pointer hover:bg-gray-750 transition-colors">
                                <div className="px-6 py-4 flex items-center justify-between">
                                    <div className="flex items-center gap-4">
                                        <svg className="h-5 w-5 text-gray-400 transition-transform group-open:rotate-90" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                                        </svg>
                                        <div>
                                            <h3 className="text-lg font-bold text-white">{accountName}</h3>
                                            <p className="text-sm text-gray-400">
                                                {sessionsCount} session{sessionsCount > 1 ? 's' : ''} • {uniqueEmployees.size} worker{uniqueEmployees.size > 1 ? 's' : ''}
                                            </p>
                                        </div>
                                    </div>
                                    <div className="text-right">
                                        <p className="text-sm text-gray-400">Total Generated</p>
                                        <p className="text-2xl font-bold text-green-400">${totalEarned.toFixed(2)}</p>
                                    </div>
                                </div>
                            </summary>

                            <div className="px-6 py-4 bg-gray-900 border-t border-gray-700">
                                <h4 className="text-sm font-medium text-gray-400 mb-3">Work Sessions:</h4>
                                <div className="space-y-3">
                                    {sessions.map((session, index) => (
                                        <div key={session.id} className="bg-gray-800 rounded-lg p-4 border border-gray-700">
                                            <div className="flex items-start justify-between mb-3">
                                                <div>
                                                    <div className="flex items-center gap-2">
                                                        <span className="text-sm font-medium text-blue-400">
                                                            {session.employee?.username || 'Unknown'}
                                                        </span>
                                                        <span className={`text-xs px-2 py-0.5 rounded-full ${
                                                            session.isPaid 
                                                                ? 'bg-green-900 text-green-300 border border-green-700' 
                                                                : 'bg-yellow-900 text-yellow-300 border border-yellow-700'
                                                        }`}>
                                                            {session.isPaid ? 'Paid' : 'Pending'}
                                                        </span>
                                                    </div>
                                                    <p className="text-xs text-gray-500 mt-1">
                                                        {session.initialEarningsDate ? new Date(session.initialEarningsDate).toLocaleDateString() : 'N/A'} 
                                                        {' → '}
                                                        {session.finalEarningsDate ? new Date(session.finalEarningsDate).toLocaleDateString() : 'N/A'}
                                                    </p>
                                                </div>
                                                <div className="text-right">
                                                    <p className="text-lg font-bold text-green-400">${session.earned.toFixed(2)}</p>
                                                    <p className="text-xs text-gray-500">
                                                        ${session.initialEarnings?.toString() || '0'} → ${session.finalEarnings?.toString() || '0'}
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    ))}
                                </div>

                                <div className="mt-4 pt-4 border-t border-gray-700 flex justify-between items-center">
                                    <span className="text-sm font-medium text-gray-400">Account Total:</span>
                                    <span className="text-xl font-bold text-green-400">${totalEarned.toFixed(2)}</span>
                                </div>
                            </div>
                        </details>
                    ))}
                </div>
            )}

            {/* Summary Stats */}
            {Object.keys(accountSummary).length > 0 && (
                <div className="bg-gray-800 rounded-lg shadow-lg border border-gray-700 p-6">
                    <h3 className="text-lg font-bold text-white mb-4">Summary</h3>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        <div>
                            <p className="text-sm text-gray-400">Total Accounts</p>
                            <p className="text-2xl font-bold text-white">{Object.keys(accountSummary).length}</p>
                        </div>
                        <div>
                            <p className="text-sm text-gray-400">Total Sessions</p>
                            <p className="text-2xl font-bold text-white">
                                {Object.values(accountSummary).reduce((sum, acc) => sum + acc.sessionsCount, 0)}
                            </p>
                        </div>
                        <div>
                            <p className="text-sm text-gray-400">Total Earnings Generated</p>
                            <p className="text-2xl font-bold text-green-400">
                                ${Object.values(accountSummary).reduce((sum, acc) => sum + acc.totalEarned, 0).toFixed(2)}
                            </p>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
