# Generated by Django 6.0 on 2025-12-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskclaim',
            name='time_spent_minutes',
        ),
        migrations.AddField(
            model_name='taskclaim',
            name='time_spent_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter time in hours (e.g. 1.5)', max_digits=5),
            preserve_default=False,
        ),
    ]
