# Generated by Django 6.0 on 2025-12-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_workaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='workaccount',
            name='date_claimed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workaccount',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
