# Generated by Django 6.0 on 2025-12-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_remove_workaccount_date_claimed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workaccount',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Accepted', 'Accepted')], default='Assigned', max_length=20),
        ),
    ]
