# Generated by Django 6.0 on 2025-12-20 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Outlier AI', 'Outlier AI'), ('Handshake', 'Handshake'), ('Other', 'Other')], max_length=50)),
                ('task_external_id', models.CharField(max_length=255)),
                ('screenshot', models.ImageField(upload_to='proofs/%Y/%m/')),
                ('time_spent_minutes', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('manager_notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'task_external_id'), name='unique_task_per_platform')],
            },
        ),
    ]
