# Generated by Django 6.0 on 2025-12-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_remove_taskclaim_time_spent_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskclaim',
            name='account_name',
            field=models.CharField(default='Default Account', help_text='Name of the account you are working on', max_length=100),
            preserve_default=False,
        ),
    ]
