# Generated by Django 6.0 on 2025-12-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_taskclaim_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskclaim',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
