# Generated by Django 6.0 on 2025-12-21 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_taskclaim_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='e.g. Facebook Ads Account 1', max_length=100)),
                ('login_details', models.TextField(help_text='Username, Password, etc.')),
                ('browser_type', models.CharField(choices=[('IX Browser', 'IX Browser'), ('GoLogin', 'GoLogin'), ('MoreLogin', 'MoreLogin'), ('Other', 'Other')], max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
