# Generated by Django 6.0 on 2025-12-22 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_workaccount_date_claimed_workaccount_is_claimed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workaccount',
            name='date_claimed',
        ),
        migrations.RemoveField(
            model_name='workaccount',
            name='is_claimed',
        ),
    ]
