# Generated by Django 6.0 on 2025-12-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_workaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workaccount',
            name='recently_unpaused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskclaim',
            name='account_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taskclaim',
            name='time_spent_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workaccount',
            name='account_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workaccount',
            name='login_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workaccount',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('Paused', 'Paused'), ('Left', 'Left')], default='Assigned', max_length=20),
        ),
    ]
